version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - krishiai-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - krishiai-network

  worker:
    build: .
    command: python worker.py
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - redis
    networks:
      - krishiai-network

networks:
  krishiai-network:
    driver: bridge

volumes:
  redis-data:
